/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class URLEncoding */

#ifndef _Included_URLEncoding
#define _Included_URLEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     URLEncoding
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_URLEncoding_encode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     URLEncoding
 * Method:    encodeBinary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_URLEncoding_encodeBinary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     URLEncoding
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_URLEncoding_decode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     URLEncoding
 * Method:    decodeBinary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_URLEncoding_decodeBinary
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
